name: chat-bot-elastic-sim
type: php
docroot: public
php_version: "8.1"
webserver_type: apache-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
  type: mariadb
  version: "10.11"
use_dns_when_possible: true
composer_version: "2"
web_environment:
  - SS_ENVIRONMENT_TYPE=dev
  - SS_DATABASE_SERVER=db
  - SS_DATABASE_NAME=db
  - SS_DATABASE_USERNAME=db
  - SS_DATABASE_PASSWORD=db
  - SS_DEFAULT_ADMIN_USERNAME=admin
  - SS_DEFAULT_ADMIN_PASSWORD=admin

# Elasticsearch service will be added via docker-compose.elasticsearch.yaml
